name: GitHub Actions Workflow

on: [schedule,push]
  # Times are in UTC, this job is run
  # daily @ 14HRS = 9AM EST, 20HRS = 3PM EST
  - cron: "0 14,20 * * *"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Test files
        run: |
          ls -la
          for f in $(find . -type f ! -ipath '*.config*' ! -ipath '*.git*' ! -ipath '*.local*' ! -ipath '*.vim*' ! -ipath '*.vscode*' ! -iname cht.sh -executable); do
            if file "${f}" | grep --quiet shell; then
              {
                shellcheck "${f}" && echo "[OK]: successfully linted ${f}"
              } || {
                ERRORS+=("${f}")
              }
            fi
          done
          if [ ${#ERRORS[@]} -eq 0 ]; then
            echo "No errors, hooray"
          else
            echo "These files failed shellcheck: ${ERRORS[*]}"
            exit 1
          fi
